# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: u4ms/_impl/config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='u4ms/_impl/config.proto',
  package='lq.config',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17u4ms/_impl/config.proto\x12\tlq.config\"T\n\x05\x46ield\x12\x12\n\nfield_name\x18\x01 \x01(\t\x12\x14\n\x0c\x61rray_length\x18\x02 \x01(\r\x12\x0f\n\x07pb_type\x18\x03 \x01(\t\x12\x10\n\x08pb_index\x18\x04 \x01(\r\"*\n\tSheetMeta\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"a\n\x0bSheetSchema\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\x04meta\x18\x02 \x01(\x0b\x32\x14.lq.config.SheetMeta\x12 \n\x06\x66ields\x18\x03 \x03(\x0b\x32\x10.lq.config.Field\"C\n\x0bTableSchema\x12\x0c\n\x04name\x18\x01 \x01(\t\x12&\n\x06sheets\x18\x02 \x03(\x0b\x32\x16.lq.config.SheetSchema\"7\n\tSheetData\x12\r\n\x05table\x18\x01 \x01(\t\x12\r\n\x05sheet\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x0c\"\x82\x01\n\x0c\x43onfigTables\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x13\n\x0bheader_hash\x18\x02 \x01(\t\x12\'\n\x07schemas\x18\x03 \x03(\x0b\x32\x16.lq.config.TableSchema\x12#\n\x05\x64\x61tas\x18\x04 \x03(\x0b\x32\x14.lq.config.SheetDatab\x06proto3'
)




_FIELD = _descriptor.Descriptor(
  name='Field',
  full_name='lq.config.Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_name', full_name='lq.config.Field.field_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='array_length', full_name='lq.config.Field.array_length', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pb_type', full_name='lq.config.Field.pb_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pb_index', full_name='lq.config.Field.pb_index', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=122,
)


_SHEETMETA = _descriptor.Descriptor(
  name='SheetMeta',
  full_name='lq.config.SheetMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='lq.config.SheetMeta.category', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='lq.config.SheetMeta.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=166,
)


_SHEETSCHEMA = _descriptor.Descriptor(
  name='SheetSchema',
  full_name='lq.config.SheetSchema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='lq.config.SheetSchema.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meta', full_name='lq.config.SheetSchema.meta', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fields', full_name='lq.config.SheetSchema.fields', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=265,
)


_TABLESCHEMA = _descriptor.Descriptor(
  name='TableSchema',
  full_name='lq.config.TableSchema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='lq.config.TableSchema.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sheets', full_name='lq.config.TableSchema.sheets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=334,
)


_SHEETDATA = _descriptor.Descriptor(
  name='SheetData',
  full_name='lq.config.SheetData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='lq.config.SheetData.table', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sheet', full_name='lq.config.SheetData.sheet', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='lq.config.SheetData.data', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=391,
)


_CONFIGTABLES = _descriptor.Descriptor(
  name='ConfigTables',
  full_name='lq.config.ConfigTables',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='lq.config.ConfigTables.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='header_hash', full_name='lq.config.ConfigTables.header_hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='schemas', full_name='lq.config.ConfigTables.schemas', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datas', full_name='lq.config.ConfigTables.datas', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=524,
)

_SHEETSCHEMA.fields_by_name['meta'].message_type = _SHEETMETA
_SHEETSCHEMA.fields_by_name['fields'].message_type = _FIELD
_TABLESCHEMA.fields_by_name['sheets'].message_type = _SHEETSCHEMA
_CONFIGTABLES.fields_by_name['schemas'].message_type = _TABLESCHEMA
_CONFIGTABLES.fields_by_name['datas'].message_type = _SHEETDATA
DESCRIPTOR.message_types_by_name['Field'] = _FIELD
DESCRIPTOR.message_types_by_name['SheetMeta'] = _SHEETMETA
DESCRIPTOR.message_types_by_name['SheetSchema'] = _SHEETSCHEMA
DESCRIPTOR.message_types_by_name['TableSchema'] = _TABLESCHEMA
DESCRIPTOR.message_types_by_name['SheetData'] = _SHEETDATA
DESCRIPTOR.message_types_by_name['ConfigTables'] = _CONFIGTABLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Field = _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), {
  'DESCRIPTOR' : _FIELD,
  '__module__' : 'u4ms._impl.config_pb2'
  # @@protoc_insertion_point(class_scope:lq.config.Field)
  })
_sym_db.RegisterMessage(Field)

SheetMeta = _reflection.GeneratedProtocolMessageType('SheetMeta', (_message.Message,), {
  'DESCRIPTOR' : _SHEETMETA,
  '__module__' : 'u4ms._impl.config_pb2'
  # @@protoc_insertion_point(class_scope:lq.config.SheetMeta)
  })
_sym_db.RegisterMessage(SheetMeta)

SheetSchema = _reflection.GeneratedProtocolMessageType('SheetSchema', (_message.Message,), {
  'DESCRIPTOR' : _SHEETSCHEMA,
  '__module__' : 'u4ms._impl.config_pb2'
  # @@protoc_insertion_point(class_scope:lq.config.SheetSchema)
  })
_sym_db.RegisterMessage(SheetSchema)

TableSchema = _reflection.GeneratedProtocolMessageType('TableSchema', (_message.Message,), {
  'DESCRIPTOR' : _TABLESCHEMA,
  '__module__' : 'u4ms._impl.config_pb2'
  # @@protoc_insertion_point(class_scope:lq.config.TableSchema)
  })
_sym_db.RegisterMessage(TableSchema)

SheetData = _reflection.GeneratedProtocolMessageType('SheetData', (_message.Message,), {
  'DESCRIPTOR' : _SHEETDATA,
  '__module__' : 'u4ms._impl.config_pb2'
  # @@protoc_insertion_point(class_scope:lq.config.SheetData)
  })
_sym_db.RegisterMessage(SheetData)

ConfigTables = _reflection.GeneratedProtocolMessageType('ConfigTables', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGTABLES,
  '__module__' : 'u4ms._impl.config_pb2'
  # @@protoc_insertion_point(class_scope:lq.config.ConfigTables)
  })
_sym_db.RegisterMessage(ConfigTables)


# @@protoc_insertion_point(module_scope)